# Generated by Django 6.0.6 on 2026-08-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationmembership',
            name='role',
        ),
        migrations.AddField(
            model_name='organizationmembership',
            name='roles',
            field=models.ManyToManyField(related_name='memberships', to='unit_app.role'),
        ),
    ]
