# Generated by Django 6.0.6 on 2026-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0002_remove_organizationmembership_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
