# Generated by Django 6.0.6 on 2026-07-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0002_package_alter_user_role_notification_serviceprovider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='email_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='logs_duration',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='package',
            name='mpesa_daraja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='package',
            name='number_of_units',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='package',
            name='month_days',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='package',
            name='year_days',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
