# Generated by Django 6.0.6 on 2026-07-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0003_package_email_notifications_package_logs_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='payment_method',
            field=models.CharField(choices=[('mpesa', 'Mpesa'), ('paystack', 'Paystack'), ('bank', 'Bank')], default='Mpesa', max_length=50),
        ),
        migrations.AddField(
            model_name='rentpayment',
            name='transaction_id',
            field=models.CharField(blank=True, default='M299920sjsjsk', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('property manager', 'Property Manager'), ('landlord', 'Landlord'), ('caretaker', 'Caretaker'), ('tenant', 'Tenant'), ('service provider', 'Service Provider'), ('equipment supplier', 'Equipment Supplier'), ('client', 'Client')], max_length=20),
        ),
    ]
