# Generated by Django 6.0.6 on 2026-07-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0004_rentpayment_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('property manager', 'Property Manager'), ('landlord', 'Landlord'), ('caretaker', 'Caretaker'), ('tenant', 'Tenant'), ('service provider', 'Service Provider'), ('store owner', 'Store Owner'), ('equipment supplier', 'Equipment Supplier'), ('client', 'Client')], max_length=20),
        ),
    ]
