# Generated by Django 6.0.6 on 2026-08-14 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0005_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembership',
            name='primary_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_memberships', to='unit_app.role'),
        ),
    ]
