# Generated by Django 6.0.6 on 2026-07-08 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0006_rename_name_store_location_store_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(default='Default Store', max_length=255),
        ),
    ]
