# Generated by Django 6.0.6 on 2026-08-17 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0007_organizationinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='amenity',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='amenity',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='unit_app.organization'),
        ),
        migrations.AddConstraint(
            model_name='amenity',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organization_amenity'),
        ),
    ]
