# Generated by Django 6.0.6 on 2026-07-08 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0007_alter_store_description_alter_store_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.CreateModel(
            name='ProductPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('mpesa', 'Mpesa'), ('card', 'Card'), ('paystack', 'Paystack')], max_length=20)),
                ('payment_status', models.CharField(choices=[('paid', 'Paid'), ('failed', 'Failed'), ('pending', 'Pending')], max_length=10)),
                ('checkout_request_id', models.CharField(default='N/A', max_length=100)),
                ('receipt_number', models.CharField(default='N/A', max_length=100)),
                ('paid_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='unit_app.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unit_app.store')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='unit_app.product')),
                ('store', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='store_sales', to='unit_app.store')),
            ],
        ),
    ]
