# Generated by Django 6.0.6 on 2026-07-08 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0009_rename_price_product_buying_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
