# Generated by Django 6.0.6 on 2026-08-19 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0009_tenantunitassignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='KaskaziMaintenanceBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_booking_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('external_worker_id', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_name', models.CharField(blank=True, max_length=255, null=True)),
                ('worker_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('service_code', models.CharField(blank=True, max_length=100, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('requested', 'Requested'), ('accepted', 'Accepted'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='requested', max_length=30)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('quoted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('final_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maintenance_ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kaskazi_booking', to='unit_app.maintenanceticket')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kaskazi_maintenance_bookings', to='unit_app.organization')),
            ],
        ),
    ]
