# Generated by Django 6.0.6 on 2026-07-08 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0011_productsale_buyer_productsale_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsale',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('on-transist', 'On-transist'), ('delivered', 'Delivered')], default='pending', max_length=20),
        ),
    ]
