# Generated by Django 6.0.6 on 2026-09-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0011_subscriptionpackage_organizationsubscription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('paystack', 'Paystack'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank Transfer'), ('manual', 'Manual'), ('other', 'Other')], max_length=30),
        ),
    ]
