# Generated by Django 6.0.6 on 2026-07-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0012_productsale_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
