# Generated by Django 6.0.6 on 2026-07-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0015_company_description_company_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='images',
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.URLField(default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png'),
        ),
    ]
