# Generated by Django 6.0.6 on 2026-07-09 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0016_remove_property_images_property_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='image',
        ),
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
