# Generated by Django 6.0.6 on 2026-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0018_company_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
