# Generated by Django 6.0.6 on 2026-07-10 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0019_company_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='city',
            field=models.CharField(blank=True, default='Nairobi', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.CharField(blank=True, default='Kenya', max_length=100, null=True),
        ),
    ]
