# Generated by Django 6.0.6 on 2026-07-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0022_companybookingpayment_companywallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
