# Generated by Django 6.0.6 on 2026-07-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0024_propertbooking_propertybookingpayment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertBooking',
            new_name='PropertyBooking',
        ),
        migrations.RenameField(
            model_name='propertybookingpayment',
            old_name='unit',
            new_name='property_booking',
        ),
    ]
