# Generated by Django 6.0.6 on 2026-07-11 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0025_rename_propertbooking_propertybooking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertybookingpayment',
            name='property_booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='unit_app.propertybooking'),
        ),
    ]
