# Generated by Django 6.0.6 on 2026-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0027_propmanagerwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='msg_type',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
