# Generated by Django 6.0.6 on 2026-07-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0028_notification_msg_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='price_per_month',
            new_name='deposit',
        ),
        migrations.AddField(
            model_name='tenant',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_back_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_front_image',
            field=models.URLField(blank=True, default='https://res.cloudinary.com/dc68huvjj/image/upload/v1748102584/kwwwa0avlfoeybpi3key.png', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='rent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='water_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house', 'House'), ('office', 'Office'), ('mall', 'Mall'), ('warehouse', 'Warehouse'), ('hostel', 'Hostel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super admin', 'Super Admin'), ('company admin', 'Company Admin'), ('property manager', 'Property Manager'), ('accountant', 'Accountant'), ('leasing officer', 'Leasing Officer'), ('maintenance officer', 'Maintenance Officer'), ('tenant', 'Tenant')], max_length=20),
        ),
    ]
