# Generated by Django 6.0.6 on 2026-07-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0030_alter_subscription_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='amenities',
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='unit',
            name='electricity_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='unit',
            name='water_meter',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
