# Generated by Django 6.0.6 on 2026-07-19 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0031_remove_unit_amenities_property_amenities_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='id_back_image',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='id_front_image',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='next_of_kin_name',
        ),
        migrations.AddField(
            model_name='tenant',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
