# Generated by Django 6.0.6 on 2026-07-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0032_remove_tenant_id_back_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='lease_end_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='lease_start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
