# Generated by Django 6.0.6 on 2026-07-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0033_alter_tenant_lease_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super admin', 'Super Admin'), ('company admin', 'Company Admin'), ('property manager', 'Property Manager'), ('accountant', 'Accountant'), ('leasing officer', 'Leasing Officer'), ('maintenance officer', 'Maintenance Officer'), ('tenant', 'Tenant'), ('landlord', 'Landlord')], max_length=20),
        ),
    ]
