# Generated by Django 6.0.6 on 2026-07-19 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0035_alter_company_description_alter_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professional_company', to='unit_app.company'),
            preserve_default=False,
        ),
    ]
