# Generated by Django 6.0.6 on 2026-07-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0036_professional_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super admin', 'Super Admin'), ('company admin', 'Company Admin'), ('property manager', 'Property Manager'), ('accountant', 'Accountant'), ('leasing officer', 'Leasing Officer'), ('maintenance officer', 'Maintenance Officer'), ('tenant', 'Tenant'), ('landlord', 'Landlord'), ('client', 'Client')], max_length=20),
        ),
    ]
