# Generated by Django 6.0.6 on 2026-07-22 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0039_maintenancerequest_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('security', 'Security'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
