# Generated by Django 6.0.6 on 2026-07-23 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0041_subscriptionpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('plumbing', 'Plumbing'), ('electrical', 'Electrical'), ('cleaning', 'Cleaning'), ('painting', 'Painting'), ('roofing', 'Roofing'), ('carpentry', 'Carpentry'), ('moving', 'Moving'), ('security', 'Security'), ('internet', 'Internet'), ('other', 'Other')], default='other', max_length=30)),
                ('minimum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('maximum_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(blank=True, help_text='Example: 1 Hour, 2 Days', max_length=100, null=True)),
                ('image', models.URLField(blank=True, help_text='Cloudinary image URL', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='unit_app.company')),
            ],
        ),
    ]
