# Generated by Django 6.0.6 on 2026-07-24 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0042_companyservice'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybooking',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='unit_app.professional'),
        ),
    ]
