# Generated by Django 6.0.6 on 2026-07-24 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unit_app', '0043_companybooking_assigned_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_company', to='unit_app.company'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
