from django.contrib import admin
from .models import User, UserProfile, UserSession, TenantUnitAssignment, OTPVerification, Organization, OrganizationBranch, Role, Permission, RolePermission, OrganizationMembership, OrganizationInvitation, Portifolio, Property, PropertyImage, Building, Floor, Unit, Amenity, PropertyAmenity, UnitAmenity, Asset, AssetDepreciationEntries, Inspection, InspectionItem, InspectionMedia, Owner, PropertyOwnership, OwnerBankAccount, Tenant, TenantEmergencyContact, TenantScreening, Lease, LeaseTenant, LeaseCharge, LeaseDeposit, LeaseRenewal, LeaseTermination, MoveRecord, Invoice, InvoiceItem, Payment, PaymentAllocation, Receipt,Penalty, PaymentReconciliation, MaintenanceTicket, MaintenanceMedia, MaintenanceComment, MaintenanceStatusHistory, MaintenanceApproval, MaintenanceWarranty, Notification, KaskaziMaintenanceBooking, SubscriptionPackage, OrganizationSubscription, SubscriptionPayment


admin.site.register(User)
admin.site.register(UserProfile)
admin.site.register(UserSession)
admin.site.register(OTPVerification)
admin.site.register(Organization)
admin.site.register(OrganizationBranch)
admin.site.register(Role)
admin.site.register(Permission)
admin.site.register(RolePermission)
admin.site.register(OrganizationMembership)
admin.site.register(OrganizationInvitation)
admin.site.register(Portifolio)
admin.site.register(Property)
admin.site.register(PropertyImage)
admin.site.register(Building)
admin.site.register(Floor)
admin.site.register(Unit)
admin.site.register(Amenity)
admin.site.register(PropertyAmenity)
admin.site.register(TenantUnitAssignment)
admin.site.register(UnitAmenity)
admin.site.register(Asset)
admin.site.register(AssetDepreciationEntries)
admin.site.register(Inspection)
admin.site.register(InspectionItem)
admin.site.register(InspectionMedia)
admin.site.register(Owner)
admin.site.register(PropertyOwnership)
admin.site.register(OwnerBankAccount)
admin.site.register(Tenant)
admin.site.register(TenantEmergencyContact)
admin.site.register(TenantScreening)
admin.site.register(Lease)
admin.site.register(LeaseTenant)
admin.site.register(LeaseCharge)
admin.site.register(LeaseDeposit)
admin.site.register(LeaseRenewal)
admin.site.register(LeaseTermination)
admin.site.register(MoveRecord)
admin.site.register(Invoice)
admin.site.register(InvoiceItem)
admin.site.register(Payment)
admin.site.register(PaymentAllocation)
admin.site.register(Receipt)
admin.site.register(Penalty)
admin.site.register(MaintenanceTicket)
admin.site.register(MaintenanceMedia)
admin.site.register(MaintenanceComment)
admin.site.register(MaintenanceStatusHistory)
admin.site.register(MaintenanceApproval)
admin.site.register(MaintenanceWarranty)
admin.site.register(Notification)
admin.site.register(KaskaziMaintenanceBooking)
admin.site.register(SubscriptionPackage)
admin.site.register(OrganizationSubscription)
admin.site.register(SubscriptionPayment)






